### ISSUE TITLE
Include reminder to start OpenSSH Authentication Agent Windows service in documentation

### ISSUE THREAD

**Issue by jamesabbottsmith** [rupor-github/ssh-agent-wsl#3]
This should have been obvious, but if the Windows service isn't running, you will get an error like the following:

    error fetching identities: agent refused operation

Fix is to open services.msc and ensure that `OpenSSH Authentication Agent` is running (and likely that it starts on automatically)

**Comment by rupor-github** [comment]
James, usage section has following: "Ensure that Windows ssh-agent service is started (you may want to switch its startup mode to "automatic")". Do you suggest stronger language?

**Comment by jamesabbottsmith** [comment]
I'm an idiot. Sorry! 
It might be helpful to reference `OpenSSH Authentication Agent` rather than `ssh-agent`. I think I just cast my eyes over the docs and saw `ssh-agent` and I thought "oh yeah, I've already done that". 
Anyway, it's my fault. Should have read instructions more carefully, particularly before posting!
