### ISSUE TITLE
Unable to delegate ssh-agent to docker

### ISSUE THREAD

**Issue by SebTardif** [rupor-github/ssh-agent-wsl#6]
I'm not sure if it's related to a 'flaw' in the implementation or an unrelated issue but the following doesn't work from WSL:

> docker run --volume $SSH_AUTH_SOCK:/ssh-agent --env SSH_AUTH_SOCK=/ssh-agent -ti pivotaldata/concourse-ssh ssh-add -l

**Comment by rupor-github** [comment]
Does not look to me like this is related to ssh-agent - rather to WSL interop implementation.

You see, I am not entirely sure that this is done right. Issuing docker command under WSL passes it to docker service running on Windows. In this case it is not obvious how it should locate AUTH socket which is normally created in /tmp directory of WSL instance running. It my case I get something like this:

`docker: Error response from daemon: invalid volume specification:` 

Do you think that in case it is workable at all path probably needs to be translated back to Windows before being passed to docker in WSL to be passed to Windows docker service?

**Comment by SebTardif** [comment]
Silly me, that doesn't make much sense how I tried to do this. I guess an approach would be to create a similar proxy on the Windows side that translate the native OpenSSH from pipe to socket. Then the socket path could be passed to Docker from Windows and/or WSL.

**Comment by rupor-github** [comment]
My  hope would be that at some point of time pipe would not be needed at all. Windows ssh-agent service will then provide socket (rather than pipe) and this would be directly useful in WSL and everywhere else :)
